[package]
name = "do-things"
version = "0.0.1"
authors = ["Jim Grandpre <jimtla@gmail.com>"]

[dependencies]
typemap = "*"
plugin = "*"
rand = "*"
router = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"

[dependencies.rethink]
path = "../rethink-rs"

[dependencies.iron]
version = "*"
